name: UDSPlugin
main: com.undeadscythes.udsplugin.UDSPlugin
version: 7.56#
description: UndeadScythes custom plugin for CB 1.4.2-R0.1 #2406.
author: Dave 'UndeadScythes' Gardner - daveyognaut2@gmail.com
website: http://undeadscythes.webs.com/
depend: [PermissionsBukkit]
softdepend: []
commands:
  a:
  acceptrules:
  admin:
  adminme:
  back:
  ban:
  blind:
  bounty:
    aliases: bounties
  broadcast:
    aliases: b
  butcher:
  c:
  call:
  challenge:
  check:
  ci:
  city:
  clan:
  day:
  debug:
  default:
  delwarp:
  enchant:
  face:
  firework:
  gift:
  giveperm:
  god:
  heal:
  help:
  home:
  i:
    aliases: item
  ignore:
  invsee:
  jail:
  kick:
  kit:
  lockdown:
  map:
  mapdupe:
  me:
  member:
  mod:
  modme:
  money:
  n:
  nick:
  night:
  ownerme:
  p:
  paybail:
  pet:
  powertool:
  private:
  r:
    aliases: reply
  rain:
  region:
  resetquarry:
  rules:
  scuba:
  server:
  serverinfo:
  setarmor:
  setperm:
  setspawn:
  setwarp:
  shop:
  signs:
  sit:
  spawn:
  spawner:
  stack:
  stats:
  storm:
  sun:
  swearjar:
  tell:
    aliases: [whisper, msg]
  tgm:
    aliases: [gm, gamemode]
  ticket:
  timereset:
  tp:
  udsreload:
  unban:
  unjail:
  unnick:
  vip:
  warden:
  warp:
    aliases: warps
  we:
  where:
  who:
    aliases: list
  whois:
  xp:
    aliases: exp
  y:

permissions:
  udsplugin.city.*:
    children:
      udsplugin.help.city: true
      udsplugin.city.banish: true
      udsplugin.city.invite: true
      udsplugin.city.leave: true
      udsplugin.city.new: true
      udsplugin.city.set: true
      udsplugin.city.warp: true

  udsplugin.clan.*:
    children:
      udsplugin.help.clan: true
      udsplugin.clan.base: true
      udsplugin.clan.invite: true
      udsplugin.clan.kick: true
      udsplugin.clan.leave: true
      udsplugin.clan.list: true
      udsplugin.clan.members: true
      udsplugin.clan.new: true
      udsplugin.clan.owner: true
      udsplugin.clan.base.clear: true
      udsplugin.clan.base.make: true
      udsplugin.clan.base.set: true
      udsplugin.clan.base.tp: true
      udsplugin.clan.rename: true
      udsplugin.clan.stats: true
  udsplugin.clan.admin.*:
    children:
      udsplugin.clan.disband: true
      udsplugin.clan.owner.any: true

  udsplugin.home.*:
    children:
      udsplugin.help.home: true
      udsplugin.home.add: true
      udsplugin.home.boot: true
      udsplugin.home.clear: true
      udsplugin.home.kick: true
      udsplugin.home.lock: true
      udsplugin.home.make: true
      udsplugin.home.roomies: true
      udsplugin.home.sell: true
      udsplugin.home.set: true
      udsplugin.home.tp: true
      udsplugin.home.tp.other: true
      udsplugin.home.unlock: true
      udsplugin.home.expand: true
  udsplugin.home.admin.*:
    children:
      udsplugin.home.tp.any: true

  udsplugin.money.*:
    children:
      udsplugin.help.money: true
      udsplugin.money.balance: true
      udsplugin.money.pay: true
      udsplugin.money.prices: true
      udsplugin.money.rank: true
  udsplugin.money.admin.*:
    children:
      udsplugin.money.grant: true
      udsplugin.money.other: true
      udsplugin.money.set: true

  udsplugin.region.*:
    children:
      udsplugin.help.region: true
      udsplugin.region.addmember: true
      udsplugin.region.del: true
      udsplugin.region.delmember: true
      udsplugin.region.flag: true
      udsplugin.region.info: true
      udsplugin.region.list: true
      udsplugin.region.owner: true
      udsplugin.region.portal: true
      udsplugin.region.rename: true
      udsplugin.region.reset: true
      udsplugin.region.select: true
      udsplugin.region.set: true
      udsplugin.region.tp: true
      udsplugin.region.vert: true
  udsplugin.region.admin.*:
    children:
      udsplugin.region.quarry: true
      udsplugin.bug.regiondel: true

  udsplugin.server.*:
    children:
      udsplugin.help.server: true
      udsplugin.server.stats: true
      udsplugin.server.stop: true

  udsplugin.shop.*:
    children:
      udsplugin.help.shop: true
      udsplugin.shop.buy: true
      udsplugin.shop.clear: true
      udsplugin.shop.fire: true
      udsplugin.shop.hire: true
      udsplugin.shop.item: true
      udsplugin.shop.sell: true
      udsplugin.shop.sign: true
      udsplugin.shop.tp: true
      udsplugin.shop.tp.other: true
      udsplugin.shop.workers: true
  udsplugin.shop.admin.*:
    children:
      udsplugin.shop.del: true
      udsplugin.shop.make: true
      udsplugin.shop.server: true
      udsplugin.shop.set: true
      udsplugin.shop.tp.any: true

  udsplugin.we.*:
    children:
      udsplugin.we.copy: true
      udsplugin.we.drain: true
      udsplugin.we.move: true
      udsplugin.we.paste: true
      udsplugin.we.regen: true
      udsplugin.we.replace: true
      udsplugin.we.set: true
      udsplugin.we.undo: true
  udsplugin.we.safe.*:
    children:
      udsplugin.help.we: true
      udsplugin.we.ext: true

  udsplugin.group.default:
    children:
      udsplugin.any: true
      udsplugin.call: true
      udsplugin.changes: true
      udsplugin.chat.help: true
      udsplugin.check: true
      udsplugin.checkpoint: true
      udsplugin.face: true
      udsplugin.gift: true
      udsplugin.help: true
      udsplugin.help.pet: true
      udsplugin.ignore: true
      udsplugin.item: true
      udsplugin.kit: true
      udsplugin.map: true
      udsplugin.me: true
      udsplugin.minecart: true
      udsplugin.money.*: true
      udsplugin.n: true
      udsplugin.r: true
      udsplugin.paybail: true
      udsplugin.pet.give: true
      udsplugin.pet.sell: true
      udsplugin.prize: true
      udsplugin.rules: true
      udsplugin.scuba: true
      udsplugin.server.info: true
      udsplugin.sit: true
      udsplugin.spawn: true
      udsplugin.spleef: true
      udsplugin.stack: true
      udsplugin.stats: true
      udsplugin.swearjar: true
      udsplugin.tell: true
      udsplugin.ticket: true
      udsplugin.warp: true
      udsplugin.where: true
      udsplugin.who: true
      udsplugin.whois: true
      udsplugin.y: true

  udsplugin.group.default.noinherit:
    children:
      udsplugin.acceptrules: true
      udsplugin.chat.default: true
      udsplugin.newbie: true

  udsplugin.group.member:
    children:
      udsplugin.group.default: true
      udsplugin.back: true
      udsplugin.bounty: true
      udsplugin.c: true
      udsplugin.challenge: true
      udsplugin.ci: true
      udsplugin.city.*: true
      udsplugin.clan.*: true
      udsplugin.home.*: true
      udsplugin.mapdupe: true
      udsplugin.p: true
      udsplugin.paper.simple: true
      udsplugin.private: true
      udsplugin.shop.*: true
      udsplugin.wand: true

  udsplugin.group.member.noinherit:
    children:
      udsplugin.chat.member: true
      udsplugin.vip: true

  udsplugin.group.vip:
    children:
      udsplugin.group.member: true
      udsplugin.back.ondeath: true
      udsplugin.compass: true
      udsplugin.help.vip: true

  udsplugin.group.vip.noinherit:
    children:
      udsplugin.chat.vip: true
      udsplugin.i.vip: true
      udsplugin.vip: true

  udsplugin.group.warden:
    children:
      udsplugin.group.vip: true
      udsplugin.help.warden: true
      udsplugin.ignore.exempt: true
      udsplugin.jail: true
      udsplugin.paper.complex: true
      udsplugin.unjail: true

  udsplugin.group.warden.noinherit:
    children:
      udsplugin.chat.warden: true
      udsplugin.i.warden: true

  udsplugin.group.mod:
    children:
      udsplugin.group.warden: true
      udsplugin.a: true
      udsplugin.ban: true
      udsplugin.bounty.remove: true
      udsplugin.broadcast: true
      udsplugin.butcher: true
      udsplugin.bypass: true
      udsplugin.clan.admin.*: true
      udsplugin.day: true
      udsplugin.default: true
      udsplugin.delwarp: true
      udsplugin.enchant: true
      udsplugin.firework: true
      udsplugin.fun.blind: true
      udsplugin.fun.setarmor: true
      udsplugin.god: true
      udsplugin.heal: true
      udsplugin.help.mod: true
      udsplugin.home.admin.*: true
      udsplugin.i: true
      udsplugin.invsee: true
      udsplugin.kick: true
      udsplugin.member: true
      udsplugin.money.admin.*: true
      udsplugin.nick: true
      udsplugin.night: true
      udsplugin.powertool: true
      udsplugin.rain: true
      udsplugin.region.*: true
      udsplugin.resetquarry: true
      udsplugin.setwarp: true
      udsplugin.shop.admin.*: true
      udsplugin.signs: true
      udsplugin.sign.checkpoint: true
      udsplugin.sign.item: true
      udsplugin.sign.minecart: true
      udsplugin.sign.prize: true
      udsplugin.sign.spleef: true
      udsplugin.sign.warp: true
      udsplugin.spawner: true
      udsplugin.storm: true
      udsplugin.sun: true
      udsplugin.tgm: true
      udsplugin.tgm.o: true
      udsplugin.tp: true
      udsplugin.unban: true
      udsplugin.unnick: true
      udsplugin.vert: true
      udsplugin.warden: true
      udsplugin.warp.all: true
      udsplugin.warp.o: true
      udsplugin.welcome.admin: true
      udsplugin.we.safe.*: true
      udsplugin.xp: true

  udsplugin.group.mod.noinherit:
    children:
      udsplugin.chat.mod: true

  udsplugin.group.admin:
    children:
      udsplugin.group.mod: true
      udsplugin.admin: true
      udsplugin.anyregion: true
      udsplugin.debug: true
      udsplugin.giveperm: true
      udsplugin.help.admin: true
      udsplugin.lockdown: true
      udsplugin.mod: true
      udsplugin.pass: true
      udsplugin.region.admin.*: true
      udsplugin.server.*: true
      udsplugin.setperm: true
      udsplugin.setspawn: true
      udsplugin.spy: true
      udsplugin.timereset: true
      udsplugin.udsreload: true
      udsplugin.we.*: true

  udsplugin.group.admin.noinherit:
    children:
      udsplugin.chat.admin: true

  udsplugin.group.owner:
    children:
      udsplugin.group.admin: true
      udsplugin.chat.owner: true
